actress: kali roses
clips:
  - name: video 1
    clips:
      - name: kali_squat
        time: 00:00:23-00:00:45
  - name: video 2
    clips:
      - name: kali_standing
        time: 00:00:23-00:00:45